<a href="https://colab.research.google.com/github/V-Rang/CSE-382M-Project/blob/main/Algorithm1_1_DMDFunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [137]:
#function arguments: X, r, dt
#Algorithm 1.1 from DMD textbook
#Things to think about: b = Phi\x1 -> calculates Moore-Penrose pseduoinvere. We could implement a Least Squares solution to compute b in Phi X b = x1

import numpy as np
import math
X = np.array([[1,2,3,14],
     [4,5,6,15],
     [7,8,9,16],
     [17,18,19,20]])
num_modes = 2
dt = 2
# t = 6

X1 = X[:,:-1]
X2 = X[:,1:]
U,S,VT = np.linalg.svd(X1)
V = VT.T
S = np.diag(S)
Ur = U[:,:num_modes]
Sr = S[:num_modes,:num_modes]
Vr = V[:,:num_modes]


Atilde = Ur.T@X2@Vr@np.linalg.inv(Sr)
[eigvals,eigvecs] = np.linalg.eig(Atilde)
eigvals = np.diag(eigvals)
Phi = X2@Vr@np.linalg.inv(Sr)@eigvecs
lam = np.diag(eigvals)
omega = []
for value in lam:
  omega.append(math.log(value,math.e)/dt)

# print(eigvals,'\n')
# print(lam,'\n')
# print(omega)

#Computing DMD solution
x1 = X[:,1]
b = np.linalg.pinv(Phi)@x1
mm1 = X1.shape[1]

time_dynamics = np.zeros( (num_modes,mm1) )
t = np.arange(0,mm1)*dt

# print(time_dynamics,'\n')

for iter in range(0,mm1):
  time_dynamics[:,iter] = np.multiply(omega,t[iter])

Xdmd = Phi@time_dynamics

print(X,'\n')
print(Xdmd)


# lam = np.diag(eigvals)


# print(Ur.T.shape)
# print(X2.shape)
# print(Vr.shape)
# print(Sr.shape)


# print(Ur@Sr@Vr)

# print(VT,'\n')
# print(V`r)

[[ 1  2  3 14]
 [ 4  5  6 15]
 [ 7  8  9 16]
 [17 18 19 20]] 

[[ 0.          8.2055133  16.41102659]
 [ 0.          6.56992548 13.13985095]
 [ 0.          4.93433766  9.86867531]
 [ 0.         -0.05150844 -0.10301688]]
